const bcrypt = require('bcryptjs')
console.log('Seeding Users')

exports.seed = function(knex, Promise) {
  return knex('users').insert([
    
    { id: 2, photo_url: "../../style/branden.jpg", first_name: 'Branden', last_name: 'Lowe', username: 'soCalBrandon', about_me: "Lorem ipsum dolor amet quinoa next level pour-over venmo cred, unicorn poke flannel synth man bun. Church-key chambray craft beer, 3 wolf moon shoreditch kinfolk echo park. Lo-fi fixie crucifix lomo salvia microdosing affogato hexagon. Readymade distillery tacos, etsy ethical cloud bread knausgaard meggings echo park selfies 8-bit art party bitters 90's. Leggings poke cray hexagon enamel pin seitan kale chips, locavore PBR&B try-hard. Flannel typewriter four dollar toast poke kinfolk.", email: 'b.lowe333@gmail.com', password: bcrypt.hashSync('branden', 8) },
    { id: 3, photo_url: "../../style/brandon.jpg", first_name: 'Brandon', last_name: 'Yu', username: 'brainyBrandon', about_me: "Fingerstache ethical cloud bread schlitz next level. Adaptogen irony fam semiotics single-origin coffee cold-pressed. Neutra distillery roof party, vexillologist vape pug gastropub lyft crucifix. Kinfolk lomo direct trade PBR&B fashion axe hella YOLO asymmetrical poutine craft beer twee celiac try-hard pop-up live-edge.", email: 'brandoncyu@gmaill.com', password: bcrypt.hashSync('brandon', 8) },
    { id: 4, photo_url: "../../style/chris.jpg", first_name: 'Chris', last_name: 'Peterson', username: 'mrChris', about_me: "Tbh kombucha cold-pressed roof party +1 pop-up cray offal trust fund. Migas shoreditch blog sustainable, squid chia marfa palo santo master cleanse meh keytar chambray post-ironic banh mi pug. Art party prism +1 banjo lyft vaporware. Lyft lo-fi mumblecore succulents. Raclette bitters literally narwhal williamsburg, coloring book helvetica sriracha authentic yr you probably haven't heard of them edison bulb.", email: 'crpete23@gmail.com', password: bcrypt.hashSync('chris', 8) },
    { id: 5, photo_url: "../../style/craig.jpg", first_name: 'Craig', last_name: 'Fell', username: 'craigLeg', about_me: "Bushwick mixtape 3 wolf moon, slow-carb schlitz beard gentrify tumeric blog raw denim green juice lomo scenester. Seitan semiotics stumptown shabby chic. Sriracha vinyl +1, man braid butcher kogi jean shorts poke cardigan tofu poutine. Listicle put a bird on it af XOXO. Offal poke tote bag green juice kinfolk etsy prism.", email: 'grendel@shmoo.com', password: bcrypt.hashSync('craig', 8) },
    { id: 6, photo_url: "../../style/diep.jpg", first_name: 'Diep', last_name: 'Truong', username: 'hungryDiep', about_me: "Small batch bespoke microdosing 8-bit hell of la croix cold-pressed freegan beard cliche retro. Offal crucifix forage, af jianbing snackwave keytar celiac pinterest ethical master cleanse listicle VHS adaptogen. Yr pug whatever, williamsburg air plant sartorial ugh iPhone four dollar toast ethical squid. Hella kinfolk pickled church-key cold-pressed polaroid hashtag raclette franzen pinterest vinyl bitters offal. Chia godard you probably haven't heard of them, VHS kombucha slow-carb single-origin coffee small batch. Everyday carry kickstarter tilde tousled 90's swag. Seitan vinyl echo park kitsch tilde pok pok pork belly lyft.", email: 'ngocdieptruong11@gmail.com', password: bcrypt.hashSync('Diep', 8) },
    { id: 7, photo_url: "../../style/hedem.jpg", first_name: 'Hedim', last_name: 'Ramirez', username: 'hedemFamMan', about_me: "Lorem ipsum dolor amet ramps typewriter YOLO, paleo coloring book four dollar toast XOXO enamel pin. Umami ugh banh mi bushwick prism fanny pack copper mug chia waistcoat. Swag seitan synth street art prism meh gastropub. Hammock vegan tousled cronut, meditation next level gochujang poutine sriracha +1 man braid semiotics. Master cleanse yr listicle meditation vinyl jianbing, schlitz hella lomo whatever brunch blue bottle thundercats leggings tumeric. Vice drinking vinegar quinoa, master cleanse put a bird on it forage fixie kombucha marfa street art intelligentsia coloring book biodiesel. Affogato mlkshk kale chips cray photo booth umami air plant la croix street art.", email: 'ody360@gmail.com', password: bcrypt.hashSync('hedim', 8) },
    { id: 1, photo_url: "../../style/jewell.jpg", first_name: 'Jewell', last_name: 'White', username: 'jollyJewell', about_me: "Etsy mixtape chillwave everyday carry semiotics 3 wolf moon photo booth wayfarers. Enamel pin echo park shoreditch XOXO, green juice scenester bicycle rights roof party pitchfork. Normcore franzen mumblecore quinoa vice DIY, pok pok brunch leggings gochujang. Prism scenester butcher, enamel pin VHS cred chillwave actually biodiesel affogato distillery austin. Kickstarter vaporware tacos 90's. Poke cronut leggings, polaroid 8-bit small batch pug sriracha.", email: 'jewellsmailbox@gmail.com', password: bcrypt.hashSync('jewell', 8) },
    { id: 8, photo_url: "../../style/dillon.jpg", first_name: 'Dillon', last_name: 'Easter', username: 'derpyDillon', about_me: "Fanny pack everyday carry blue bottle 8-bit literally post-ironic. Butcher vaporware kale chips deep v. Selfies woke squid quinoa salvia lo-fi viral lyft cray shaman. Banh mi palo santo pabst pork belly, banjo tilde gochujang keffiyeh humblebrag offal messenger bag cornhole leggings etsy try-hard. Intelligentsia vice schlitz succulents, swag trust fund pickled lomo enamel pin man braid. Organic vegan retro deep v godard raw denim, cloud bread tote bag literally.", email: 'johndilloneaster@gmail.com', password: bcrypt.hashSync('dillon', 8) },
    { id: 9, photo_url: "../../style/nate.jpg", first_name: 'Nate', last_name: 'Semmler', username: 'nateTheGreat', about_me: "Air plant 3 wolf moon humblebrag stumptown lomo. Man braid microdosing umami pitchfork pinterest kale chips organic cloud bread. Roof party blog offal freegan pickled, kinfolk irony photo booth lo-fi thundercats skateboard banh mi franzen pour-over paleo. Cred iPhone poke chambray swag. Williamsburg flexitarian taiyaki wolf twee pork belly asymmetrical schlitz cloud bread affogato waistcoat sriracha meggings cliche banh mi. Tumblr fixie art party farm-to-table seitan prism lumbersexual kale chips swag kitsch heirloom. Polaroid cliche brooklyn, biodiesel sartorial iPhone distillery vape.", email: 'ndsunc@gmail.com', password: bcrypt.hashSync('nate', 8) },
    { id: 10, photo_url: "../../style/surya.jpg", first_name: 'Surya', last_name: 'Krishna Moorthy', username: 'sunnySurya', about_me: "Master cleanse everyday carry celiac, farm-to-table man braid 3 wolf moon vegan messenger bag disrupt glossier. Live-edge vexillologist hot chicken, synth copper mug ennui plaid brooklyn seitan. Yuccie cloud bread helvetica, messenger bag leggings kinfolk trust fund stumptown tote bag polaroid mixtape. Cold-pressed sartorial vinyl literally, tacos church-key hexagon humblebrag taiyaki austin street art XOXO.", email: 'ayrus2289@gmail.com', password: bcrypt.hashSync('surya', 8) },
    { id: 11, photo_url: "../../style/wendy.jpg", first_name: 'Wendy', last_name: 'Parsons', username: 'trendyWendy', about_me: "Franzen salvia deep v bitters vape schlitz fashion axe biodiesel. Squid tumeric vinyl, taxidermy leggings locavore health goth vexillologist butcher. Biodiesel wayfarers kombucha snackwave jianbing 90's leggings af pug food truck iceland YOLO truffaut shaman readymade. Street art woke post-ironic, brunch hot chicken wayfarers mumblecore bicycle rights lo-fi sriracha scenester 90's iceland asymmetrical. 3 wolf moon cray mlkshk four loko. Paleo kogi you probably haven't heard of them synth meh. 3 wolf moon four loko gochujang wayfarers lo-fi deep v hoodie.", email: 'wsparsons@gmail.com', password: bcrypt.hashSync('wendy', 8) },
    { id: 12, photo_url: "../../style/justin.jpg", first_name: 'Justin', last_name: 'Hays', username: 'justinTime', about_me: "Try-hard polaroid messenger bag, literally vape pok pok swag fashion axe williamsburg keffiyeh actually. YOLO af succulents vexillologist activated charcoal, venmo typewriter pork belly forage. +1 portland small batch, hoodie pok pok try-hard vaporware vegan 8-bit pinterest affogato fixie XOXO asymmetrical. Narwhal freegan twee man bun gochujang. Viral tumblr fingerstache banh mi chicharrones street art art party hella pitchfork brooklyn retro hot chicken chartreuse poutine messenger bag.", email: 'justin@gmail.com', password: bcrypt.hashSync('justin', 8) },
    { id: 13, photo_url: "../../style/wes.jpg", first_name: 'Wes', last_name: 'Reid', username: 'wittyWes', about_me: "You probably haven't heard of them wolf deep v irony umami chillwave four loko williamsburg cliche waistcoat unicorn helvetica pickled selvage. Swag helvetica bitters kickstarter bushwick humblebrag pitchfork activated charcoal banh mi. Kinfolk pinterest mustache, echo park pabst unicorn pop-up messenger bag gluten-free waistcoat semiotics street art 90's. Fashion axe lomo seitan bitters actually literally succulents fixie gentrify freegan keytar subway tile. Pour-over cred food truck normcore, subway tile vaporware tote bag brooklyn schlitz intelligentsia kogi neutra plaid.", email: 'wes@gmail.com', password: bcrypt.hashSync('wes', 8) },
    { id: 14, photo_url: "../../style/scott.jpg", first_name: 'scottsAlot', last_name: 'Hurlow', username: 'scottsAlot', about_me: "Air plant 3 wolf moon humblebrag stumptown lomo. Man braid microdosing umami pitchfork pinterest kale chips organic cloud bread. Roof party blog offal freegan pickled, kinfolk irony photo booth lo-fi thundercats skateboard banh mi franzen pour-over paleo. Cred iPhone poke chambray swag. Williamsburg flexitarian taiyaki wolf twee pork belly asymmetrical schlitz cloud bread affogato waistcoat sriracha meggings cliche banh mi. Tumblr fixie art party farm-to-table seitan prism lumbersexual kale chips swag kitsch heirloom. Polaroid cliche brooklyn, biodiesel sartorial iPhone distillery vape.", email: 'scott@gmail.com', password: bcrypt.hashSync('scott', 8) },
  ])
  .then(() => {
    return knex.raw(`SELECT setval('users_id_seq', (SELECT MAX(id) FROM users))`)
  })
}
